### ISSUE TITLE
Django in web ui error

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/django#44]
```
java.lang.IllegalStateException: A project is required in the current context
  at org.jboss.forge.addon.projects.ui.AbstractProjectCommand.getSelectedProject(AbstractProjectCommand.java:86)
  at io.fabric8.forge.ipaas.ConnectorSelectComponentStep.initializeUI(ConnectorSelectComponentStep.java:151)



  Caused by: java.lang.IllegalStateException: A project is required in the current context
  at org.jboss.forge.addon.projects.ui.AbstractProjectCommand.getSelectedProject(AbstractProjectCommand.java:86)
  at io.fabric8.forge.ipaas.ConnectorSelectComponentStep.initializeUI(ConnectorSelectComponentStep.java:151)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
```

Got django installed in fabric8-forge and it gives some errors in the wizards. Forge is a pain to build commands when you have more than 1 screen and its bad lifecycle and calling the methods over and over again. And they are called in opposite order when executing.

**Comment by davsclaus** [comment]
![screen shot 2016-09-29 at 7 03 06 pm](https://cloud.githubusercontent.com/assets/477100/18964218/3a148b9e-8678-11e6-8905-14a4d3332534.png)

**Comment by davsclaus** [comment]
There is a NPE fix merged now.
